// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJRWgA9wWNh58uXnOV2QoZcKpG_x9o18Y',
    appId: '1:988507898334:android:c5ca2095c1ce765583dd4f',
    messagingSenderId: '988507898334',
    projectId: 'plantory-b3649',
    storageBucket: 'plantory-b3649.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfForSWMRz0eQam31EwRpUJ3Uozsj0x6I',
    appId: '1:988507898334:ios:307e35e44f731e1583dd4f',
    messagingSenderId: '988507898334',
    projectId: 'plantory-b3649',
    storageBucket: 'plantory-b3649.appspot.com',
    androidClientId: '988507898334-rdk375ef2pbn7habfl5fqm5hekc3nbse.apps.googleusercontent.com',
    iosClientId: '988507898334-v3ogr9emclfl07r9525ger8helgr7g2o.apps.googleusercontent.com',
    iosBundleId: 'com.vanillajaem.plantory',
  );
}
